name: Security Code Review on PR
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: ca-risken/security-review@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          risken_console_url: 'https://console.security-hub.jp'
          risken_api_endpoint: 'https://api.security-hub.jp'
          risken_api_token: ${{ secrets.RISKEN_API_TOKEN }}
